version: '3'

tasks:
  install:
    desc: Installs docsify to work the on the documentation site
    cmds:
      - npm install docsify-cli -g

  serve:
    desc: Serves the documentation site locally
    cmds:
      - docsify serve .

  ico:
    desc: Generate favicon.ico from Logo.png
    cmds:
      - convert -background transparent "Logo.png" -define icon:auto-resize=16,24,32,48,64,72,96,128,256 "favicon.ico"
